FROM charlie-base:v1

MAINTAINER server Docker Maintainers "charlie7zhu@outlook.com"
COPY requirements /requirements

RUN mkdir /charlie
RUN pip install --ignore-installed -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com -r requirements




